disabled_rules:
  - multiple_closures_with_trailing_closure
  - identifier_name
  - trailing_comma
  - large_tuple

line_length:
  warning: 200
  error: 300

file_length:
  warning: 1000
  error: 2000

type_body_length:
  warning: 400
  error: 800

function_body_length:
  warning: 100
  error: 200

excluded:
  - MurmurTests
