name: Murmur

include:
  - path: project.local.yml

options:
  bundleIdPrefix: com.damsac.murmur
  deploymentTarget:
    iOS: "17.0"

  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

packages:
  MurmurCore:
    path: Packages/MurmurCore

targets:
  Murmur:
    type: application
    platform: iOS
    sources:
      - path: Murmur
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: MurmurCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER_MURMUR)
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: Murmur/Murmur.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: true
    info:
      path: Murmur/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        AppGroupIdentifier: "$(APP_GROUP_IDENTIFIER)"
        NSMicrophoneUsageDescription: "Murmur uses the microphone to capture your voice notes and turn them into organized entries."
        NSSpeechRecognitionUsageDescription: "Murmur uses speech recognition to transcribe your voice notes."
    entitlements:
      path: Murmur/Murmur.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.damsac.murmur.shared
    scheme:
      testTargets:
        - MurmurTests

  MurmurTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MurmurTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Murmur
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER_TESTS)
        GENERATE_INFOPLIST_FILE: true
